name: Run Python wind

on:
  workflow_dispatch:  # Manual trigger via GitHub Actions UI

jobs:
  run-python:
    runs-on: self-hosted  # Target your local Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Python script
        run: 'C:\Python310\python.exe script.py'
