name: Run Python Script on Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: [self-hosted, LAPTOP-JCA9TBLR]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run script
        run: python script.py
