name: Run Python Script on Self-Hosted Runner

on:
  workflow_dispatch:  # This makes it manually triggerable

jobs:
  run-python:
    runs-on: self-hosted  # 💡 THIS is the key line
    steps:
      - name: Echo Hello
        run: echo "Hello from self-hosted runner!"
