name: Simple Echo Workflow

on:
  workflow_dispatch:

jobs:
  echo-job:
    runs-on: [self-hosted, LAPTOP-JCA9TBLR]

    steps:
      - name: Echo message
        run: echo "Hello from GitHub Actions on self-hosted runner!"
